version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "10010:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always

volumes:
  db_data:
